Новый тег и новый фильтр
thinknetica-django-lab-02/GorkyCow pull request #28
Opened 2021-04-03 13:44 UTC by GorkyCow

Closes #17

2021-04-03 13:47 UTC, GorkyCow commented
А, забыл написать. Вместо фильтра, который инвертирует текст я сделал фильтр, который делает текст похожим на то, как иногда его вижу я

2021-04-03 20:42 UTC, mikhailborodin requested changes

2021-04-03 20:42 UTC, mikhailborodin commented on e_commerce/main/templatetags/main_extras.py
> +def dyslexia(value):
вы слишком усложнили решение, всё гораздо проще делается через `val[::-1]`

2021-04-05 08:45 UTC, mikhailborodin approved these changes

2021-04-05 11:58 UTC, merged